
name: build ci

on: [push, pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  find_flaky:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Run Flaky Test
        run: mvn -pl retrofit test -Dtest="retrofit2.CompletableFutureAndroidTest#completableFutureApi24"
